/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Grupa;
import domen.Sala;
import domen.TipTreninga;
import domen.Trener;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Bogdan Blagojevic
 */
public class DodajTreningForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajTreningForma
     */
    public DodajTreningForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDatumTreninga = new javax.swing.JTextField();
        jComboBoxTipTreninga = new javax.swing.JComboBox<>();
        jComboBoxSala = new javax.swing.JComboBox<>();
        jComboBoxTrener = new javax.swing.JComboBox<>();
        jComboBoxGrupa = new javax.swing.JComboBox<>();
        jButtonDodajTrening = new javax.swing.JButton();
        jButtonGlavniMeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datum treninga:");

        jLabel2.setText("Tip treninga:");

        jLabel3.setText("Sala:");

        jLabel4.setText("Trener:");

        jLabel5.setText("Grupa:");

        jTextFieldDatumTreninga.setText("format: yyyy-MM-dd");

        jComboBoxTipTreninga.setModel(new DefaultComboBoxModel(TipTreninga.values())
        );

        jButtonDodajTrening.setText("Dodaj trening");

        jButtonGlavniMeni.setText("Glavni meni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDatumTreninga, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipTreninga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTrener, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGrupa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jButtonDodajTrening)))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGlavniMeni)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGlavniMeni)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDatumTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButtonDodajTrening)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajTrening;
    private javax.swing.JButton jButtonGlavniMeni;
    private javax.swing.JComboBox<Grupa> jComboBoxGrupa;
    private javax.swing.JComboBox<Sala> jComboBoxSala;
    private javax.swing.JComboBox<String> jComboBoxTipTreninga;
    private javax.swing.JComboBox<Trener> jComboBoxTrener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldDatumTreninga;
    // End of variables declaration//GEN-END:variables

    public void addDodajTreningActionListener(ActionListener actionListener) {
        jButtonDodajTrening.addActionListener(actionListener);
    }

    public JButton getjButtonDodajTrening() {
        return jButtonDodajTrening;
    }

    public void setjButtonDodajTrening(JButton jButtonDodajTrening) {
        this.jButtonDodajTrening = jButtonDodajTrening;
    }

    public JComboBox<Grupa> getjComboBoxGrupa() {
        return jComboBoxGrupa;
    }

    public void setjComboBoxGrupa(JComboBox<Grupa> jComboBoxGrupa) {
        this.jComboBoxGrupa = jComboBoxGrupa;
    }

    public JComboBox<Sala> getjComboBoxSala() {
        return jComboBoxSala;
    }

    public void setjComboBoxSala(JComboBox<Sala> jComboBoxSala) {
        this.jComboBoxSala = jComboBoxSala;
    }

    public JComboBox<String> getjComboBoxTipTreninga() {
        return jComboBoxTipTreninga;
    }

    public void setjComboBoxTipTreninga(JComboBox<String> jComboBoxTipTreninga) {
        this.jComboBoxTipTreninga = jComboBoxTipTreninga;
    }

    public JComboBox<Trener> getjComboBoxTrener() {
        return jComboBoxTrener;
    }

    public void setjComboBoxTrener(JComboBox<Trener> jComboBoxTrener) {
        this.jComboBoxTrener = jComboBoxTrener;
    }

    public JTextField getjTextFieldDatumTreninga() {
        return jTextFieldDatumTreninga;
    }

    public void setjTextFieldDatumTreninga(JTextField jTextFieldDatumTreninga) {
        this.jTextFieldDatumTreninga = jTextFieldDatumTreninga;
    }
    
    public void addGlavniMeniActionListener(ActionListener actionListener){
        jButtonGlavniMeni.addActionListener(actionListener);
    }
    
}
