/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Administrator;
import domen.Kategorija;
import domen.Trener;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Bogdan Blagojevic
 */
public class DodajGrupuForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajGrupuForma
     */
    public DodajGrupuForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivGrupe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBrojClanova = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKategorija = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxAdministrator = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTrener = new javax.swing.JComboBox<>();
        jButtonDodajGrupu = new javax.swing.JButton();
        jButtonGlavniMeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv grupe:");

        jLabel2.setText("Broj clanova:");

        jLabel3.setText("Kategorija:");

        jLabel4.setText("Administrator:");

        jLabel5.setText("Trener:");

        jButtonDodajGrupu.setText("Dodaj grupu");

        jButtonGlavniMeni.setText("Glavni meni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNazivGrupe)
                                    .addComponent(jTextFieldBrojClanova)
                                    .addComponent(jComboBoxKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxAdministrator, 0, 199, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTrener, 0, 199, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jButtonDodajGrupu)))
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGlavniMeni)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButtonGlavniMeni)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNazivGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButtonDodajGrupu)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonDodajGrupu() {
        return jButtonDodajGrupu;
    }

    public void setjButtonDodajGrupu(JButton jButtonDodajGrupu) {
        this.jButtonDodajGrupu = jButtonDodajGrupu;
    }

    public JComboBox<Administrator> getjComboBoxAdministrator() {
        return jComboBoxAdministrator;
    }

    public void setjComboBoxAdministrator(JComboBox<Administrator> jComboBoxAdministrator) {
        this.jComboBoxAdministrator = jComboBoxAdministrator;
    }

    public JComboBox<Kategorija> getjComboBoxKategorija() {
        return jComboBoxKategorija;
    }

    public void setjComboBoxKategorija(JComboBox<Kategorija> jComboBoxKategorija) {
        this.jComboBoxKategorija = jComboBoxKategorija;
    }

    public JComboBox<Trener> getjComboBoxTrener() {
        return jComboBoxTrener;
    }

    public void setjComboBoxTrener(JComboBox<Trener> jComboBoxTrener) {
        this.jComboBoxTrener = jComboBoxTrener;
    }

    public JTextField getjTextFieldBrojClanova() {
        return jTextFieldBrojClanova;
    }

    public void setjTextFieldBrojClanova(JTextField jTextFieldBrojClanova) {
        this.jTextFieldBrojClanova = jTextFieldBrojClanova;
    }

    public JTextField getjTextFieldNazivGrupe() {
        return jTextFieldNazivGrupe;
    }

    public void setjTextFieldNazivGrupe(JTextField jTextFieldNazivGrupe) {
        this.jTextFieldNazivGrupe = jTextFieldNazivGrupe;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajGrupu;
    private javax.swing.JButton jButtonGlavniMeni;
    private javax.swing.JComboBox<Administrator> jComboBoxAdministrator;
    private javax.swing.JComboBox<Kategorija> jComboBoxKategorija;
    private javax.swing.JComboBox<Trener> jComboBoxTrener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldBrojClanova;
    private javax.swing.JTextField jTextFieldNazivGrupe;
    // End of variables declaration//GEN-END:variables

    public void addDodajGrupuActionListener(ActionListener actionListener) {
        jButtonDodajGrupu.addActionListener(actionListener);
    }
    
    public void addGlavniMeniActionListener(ActionListener actionListener){
        jButtonGlavniMeni.addActionListener(actionListener);
    }
}
