/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import kordinator.Kordinator;

/**
 *
 * @author Bogdan Blagojevic
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximize the window
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        setLayout(new BorderLayout());
        
        ImageIcon grb = new ImageIcon("src/resources/img/grbnajnoviji.jpg");
        jLabelGrb.setIcon(grb);
        jLabelGrb.setHorizontalAlignment(JLabel.CENTER);
        jLabelGrb.setVerticalAlignment(JLabel.CENTER);
        add(jLabelGrb, BorderLayout.CENTER);
        
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new BorderLayout());
        
        JPanel labelPanel = new JPanel();  // A panel to hold the labels
        labelPanel.setLayout(new FlowLayout(FlowLayout.CENTER));  // Center align labels
        labelPanel.add(jLabel1);
        labelPanel.add(jLabelKorisnickoIme);

        bottomPanel.add(labelPanel, BorderLayout.CENTER);
        add(bottomPanel, BorderLayout.SOUTH);
        
         setJMenuBar(jMenuBar1);
         pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelKorisnickoIme = new javax.swing.JLabel();
        jLabelGrb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemDodajClana = new javax.swing.JMenuItem();
        jMenuItemPregledClana = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemDodajTrenera = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDodajGrupu = new javax.swing.JMenuItem();
        jMenuItemPregledGrupa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDodajTrening = new javax.swing.JMenuItem();
        jMenuItemPregledTreninga = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ulogovani korisnik: ");

        jLabelKorisnickoIme.setText("korisnicko ime");

        jLabelGrb.setPreferredSize(new java.awt.Dimension(800, 500));

        jMenu4.setText("Clan");

        jMenuItemDodajClana.setText("Dodaj");
        jMenuItemDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajClanaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDodajClana);

        jMenuItemPregledClana.setText("Pregled");
        jMenuItemPregledClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledClanaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPregledClana);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Trener");

        jMenuItemDodajTrenera.setText("Dodaj");
        jMenuItemDodajTrenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTreneraActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDodajTrenera);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Grupa");

        jMenuItemDodajGrupu.setText("Dodaj");
        jMenuItemDodajGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajGrupuActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDodajGrupu);

        jMenuItemPregledGrupa.setText("Pregled");
        jMenuItemPregledGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledGrupaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPregledGrupa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Trening");

        jMenuItemDodajTrening.setText("Dodaj");
        jMenuItemDodajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTreningActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDodajTrening);

        jMenuItemPregledTreninga.setText("Pregled");
        jMenuItemPregledTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledTreningaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPregledTreninga);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGrb, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabelGrb, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelKorisnickoIme)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDodajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTreningActionPerformed
        System.out.println("USAO U MENI DODAJ TRENING");
        Kordinator.getInstanca().otvoriDodajTreningFormu();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDodajTreningActionPerformed

    private void jMenuItemPregledClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledClanaActionPerformed
        Kordinator.getInstanca().otvoriPrikazClanaFormu();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPregledClanaActionPerformed

    private void jMenuItemDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajClanaActionPerformed
        Kordinator.getInstanca().otvoriDodajClanaFormu();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDodajClanaActionPerformed

    private void jMenuItemPregledGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledGrupaActionPerformed
    Kordinator.getInstanca().otvoriPrikazGrupaFormu();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPregledGrupaActionPerformed

    private void jMenuItemDodajGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajGrupuActionPerformed
        Kordinator.getInstanca().otvoriDodajGrupuForma();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDodajGrupuActionPerformed

    private void jMenuItemPregledTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledTreningaActionPerformed
        Kordinator.getInstanca().otvoriPrikazTreningaFormu();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPregledTreningaActionPerformed

    private void jMenuItemDodajTreneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTreneraActionPerformed
        System.out.println("USAO U DODAJ TRENERA MENI");
        Kordinator.getInstanca().otvoriDodajTreneraFormu();
        System.out.println("U MENIJU USPESNO POZVAO OTVORI DODAJ TRENERA FORMU");
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDodajTreneraActionPerformed

    public JLabel getjLabelKorisnickoIme() {
        return jLabelKorisnickoIme;
    }

    public void setjLabelKorisnickoIme(JLabel jLabelKorisnickoIme) {
        this.jLabelKorisnickoIme = jLabelKorisnickoIme;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGrb;
    private javax.swing.JLabel jLabelKorisnickoIme;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDodajClana;
    private javax.swing.JMenuItem jMenuItemDodajGrupu;
    private javax.swing.JMenuItem jMenuItemDodajTrenera;
    private javax.swing.JMenuItem jMenuItemDodajTrening;
    private javax.swing.JMenuItem jMenuItemPregledClana;
    private javax.swing.JMenuItem jMenuItemPregledGrupa;
    private javax.swing.JMenuItem jMenuItemPregledTreninga;
    // End of variables declaration//GEN-END:variables
}
